#default configuration
spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
server:
  port: 8085
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
---
spring:  
  profiles: test
server:  
  port: 8088
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
debug: true