server:
  port: 8080
management:
  security:
    enabled: false
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#    healthcheck:
#          enabled: true
#  instance:
#    preferIpAddress: true