server:
  port: 9999
management:
  security:
    enabled: false
spring:
  cloud:
    gateway:
      routes:
        - predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1
          uri: "http://localhost:8080"