server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
          enabled: true
  instance:
    preferIpAddress: true
spring.cloud.config.discovery.enabled: true
spring.cloud.config.profile: default
spring.cloud.config.discovery.serviceId: config-server