server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          url: https://github.com/gp15237125756/microservice-explore.git
          searchPaths: schedule-common-config/src/main/resources/properties

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
    healthcheck:
          enabled: true
  server:
    waitTimeInMsWhenSyncEmpty: 0

spring.cloud.config.discovery.enabled: true