server:
  port: 8888
spring:
  cloud:
    config:
      server:
        native:
          searchLocations: configuration
        git:
          uri: https://github.com/gp15237125756/microservice-explore.git
          searchPaths: configuration
          username:
          password:
  sleuth:
    traceId128: true
    sampler:
      probability: 1.0
management:
  security:
    enabled: false
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
          enabled: true
  server:
    waitTimeInMsWhenSyncEmpty: 0
logging:
  level:
    org:
      springframework:
        web: DEBUG
# Adds trace and span IDs to logs (when a trace is in progress)