server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gp15237125756/microservice-explore.git
          searchPaths: schedule-common-config/src/main/resources/properties
management:
  security:
    enabled: false
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
          enabled: true
  server:
    waitTimeInMsWhenSyncEmpty: 0