server:
  port: 8081
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
#spring.cloud.config.profile: dev
#spring.cloud.config.discovery.serviceId: config-server